networks:
  proxy:
    external: true
  db:
    internal: true

volumes:
  db_data:
  uploads_data:

services:
  db:
    image: postgres:15
    container_name: wineacademy_db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: wineacademy_backend
    command: ["npm", "run", "start"]
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=1337
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - uploads_data:/app/public/uploads
    networks:
      - db
      - proxy
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.services.backend.loadbalancer.server.port: "1337"
      traefik.http.routers.backend.rule: "Host(`wineacademymain.plan-p.de`) && PathPrefix(`/api`)"
      traefik.http.routers.backend.entrypoints: "websecure"
      traefik.http.routers.backend.tls.certresolver: "http-resolver"
      traefik.http.routers.backend.priority: "100"
      # Serve uploads without /api prefix for frontend asset URLs
      traefik.http.routers.backend-uploads.rule: "Host(`wineacademymain.plan-p.de`) && PathPrefix(`/uploads`)"
      traefik.http.routers.backend-uploads.entrypoints: "websecure"
      traefik.http.routers.backend-uploads.tls.certresolver: "http-resolver"
      traefik.http.routers.backend-uploads.priority: "100"
      # Admin/Plugin APIs used by the Strapi admin
      traefik.http.routers.backend-adminapi.rule: "Host(`wineacademymain.plan-p.de`) && (PathPrefix(`/content-manager`) || PathPrefix(`/content-type-builder`) || PathPrefix(`/i18n`) || PathPrefix(`/users-permissions`) || PathPrefix(`/email`) || PathPrefix(`/upload`) || PathPrefix(`/users`))"
      traefik.http.routers.backend-adminapi.entrypoints: "websecure"
      traefik.http.routers.backend-adminapi.tls.certresolver: "http-resolver"
      traefik.http.routers.backend-adminapi.priority: "100"
      # Serve Strapi Admin under /admin (no strip)
      traefik.http.routers.backend-admin.rule: "Host(`wineacademymain.plan-p.de`) && PathPrefix(`/admin`)"
      traefik.http.routers.backend-admin.entrypoints: "websecure"
      traefik.http.routers.backend-admin.tls.certresolver: "http-resolver"
      traefik.http.routers.backend-admin.priority: "100"

  frontend:
    build:
      context: ./frontend
    container_name: wineacademy_frontend
    env_file:
      - .env
    environment:
      - PORT=3000
    networks:
      - proxy
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.services.frontend.loadbalancer.server.port: "3000"
      traefik.http.routers.frontend.rule: "Host(`wineacademymain.plan-p.de`)"
      traefik.http.routers.frontend.entrypoints: "websecure"
      traefik.http.routers.frontend.tls.certresolver: "http-resolver"
      traefik.http.routers.frontend.priority: "1"
