import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from '@/lib/cart-context';
import CartSidebar from '@/components/cart/CartSidebar';
import CartToggle from '@/components/cart/CartToggle';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <CartProvider>
          <nav className="flex items-center justify-between border-b px-6 py-4">
            <div className="space-x-4 text-sm">
              <Link href="/" className="hover:underline">Home</Link>
              <Link href="/seminare" className="hover:underline">Seminare</Link>
              <Link href="/produkte" className="hover:underline">Produkte</Link>
              <Link href="/gutschein" className="hover:underline">Gutschein</Link>
            </div>
            <CartToggle />
          </nav>
          <main>{children}</main>
          <CartSidebar />
        </CartProvider>
      </body>
    </html>
  );
}
